import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  orders: [
    {
      serialNumber: 1,
      productLink: 'https://order-link.com/orders/randomnumber',
      id: 'orderid',
      unitPrice: 20000,
      quantity: 5,
      subTotal: 100000,
      fee: 5000,
      total: 105000,
      action: 'del',
    },
    {
      serialNumber: 2,
      productLink: 'https://order-link.com/orders/randomnumber',
      id: 'orderid',
      unitPrice: 20000,
      quantity: 5,
      subTotal: 100000,
      fee: 5000,
      total: 105000,
      action: 'del',
    },
    {
      serialNumber: 3,
      productLink: 'https://order-link.com/orders/randomnumber',
      id: 'orderid',
      unitPrice: 20000,
      quantity: 5,
      subTotal: 100000,
      fee: 5000,
      total: 105000,
      action: 'del',
    },
    {
      serialNumber: 4,
      productLink: 'https://order-link.com/orders/randomnumber',
      id: 'orderid',
      unitPrice: 20000,
      quantity: 5,
      subTotal: 100000,
      fee: 5000,
      total: 105000,
      action: 'del',
    },
    {
      serialNumber: 5,
      productLink: 'https://order-link.com/orders/randomnumber',
      id: 'orderid',
      unitPrice: 20000,
      quantity: 5,
      subTotal: 100000,
      fee: 5000,
      total: 105000,
      action: 'del',
    },
    {
      serialNumber: 6,
      productLink: 'https://order-link.com/orders/randomnumber',
      id: 'orderid',
      unitPrice: 20000,
      quantity: 5,
      subTotal: 100000,
      fee: 5000,
      total: 105000,
      action: 'del',
    },
    {
      serialNumber: 7,
      productLink: 'https://order-link.com/orders/randomnumber',
      id: 'orderid',
      unitPrice: 20000,
      quantity: 5,
      subTotal: 100000,
      fee: 5000,
      total: 105000,
      action: 'del',
    },
    {
      serialNumber: 8,
      productLink: 'https://order-link.com/orders/randomnumber',
      id: 'orderid',
      unitPrice: 20000,
      quantity: 5,
      subTotal: 100000,
      fee: 5000,
      total: 105000,
      action: 'del',
    },
    {
      serialNumber: 9,
      productLink: 'https://order-link.com/orders/randomnumber',
      id: 'orderid',
      unitPrice: 20000,
      quantity: 5,
      subTotal: 100000,
      fee: 5000,
      total: 105000,
      action: 'del',
    },
    {
      serialNumber: 10,
      productLink: 'https://order-link.com/orders/randomnumber',
      id: 'orderid',
      unitPrice: 20000,
      quantity: 5,
      subTotal: 100000,
      fee: 5000,
      total: 105000,
      action: 'del',
    },
    {
      serialNumber: 11,
      productLink: 'https://order-link.com/orders/randomnumber',
      id: 'orderid',
      unitPrice: 20000,
      quantity: 5,
      subTotal: 100000,
      fee: 5000,
      total: 105000,
      action: 'del',
    },
  ],
  orderCategories: [
    { name: 'Items in cart', key: 'itemsincart' },
    { name: 'Pending', key: 'pending' },
    { name: 'Processing', key: 'processing' },
    { name: 'Processed', key: 'processed' },
    { name: 'Received', key: 'received' },
    { name: 'Shipped', key: 'shipped' },
  ],
};

const ordersSlice = createSlice({
  name: 'orders',
  initialState,
  reducers: {},
});

export default ordersSlice.reducer;